version: "3.4"

services:
  postgresql:
    image: postgres:9.6-alpine
    container_name: postgresql
    hostname: postgresql
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  binomo:
    image: binomo
    container_name: binomo
    hostname: binomo
    command: tail -f /dev/null
    restart: always
    ports:
      - '3000:3000'
      - '8080:8080'
    volumes:
    volumes:
      - ./smoke-binomo:/app
      - postgresql_data:/var/lib/postgresql/data
    depends_on:
    - postgresql

volumes:
  postgresql_data:
    driver: local
