version: "3.4"

services:
  postgresql:
    image: postgres:10.4
    container_name: postgresql
    hostname: postgresql
    restart: always
    ports:
      - '5432:5432'
    environment:
      - LEVEL=dev
      - POSTGRES_USER:'binomo'
      - POSTGRES_PASSWORD:'binomo'
      - POSTGRES_DB:'binomo'

  binomo:
    build:
      context: ./
    container_name: binomo
    hostname: binomo
    command: tail -f /dev/null
  
    ports:
      - '3001:3000'
      - '8080:8080'
    volumes:
      - ./:/app
    depends_on:
      - postgresql