version: "3.4"

services:
  postgresql:
    image: postgres:9.6
    container_name: postgresql
    hostname: postgresql
    restart: always
    ports:
      - '5432:5432'
    environment:
      - LEVEL=dev
      - POSTGRES_USER:'binomo'
      - POSTGRES_PASSWORD:'binomo'
      - POSTGRES_DB:'binomo'
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  binomo:
    build:
      context: ./
    container_name: binomo
    hostname: binomo
    command: rails s
    restart: always
    ports:
      - '3001:3001'
      - '8080:8080'
    volumes:
      - ./:/app
    depends_on:
      - postgresql

volumes:
  postgresql_data:
    driver: local
