version: "3.4"

services:
  postgresql1:
    image: postgres:10.4
    container_name: postgresql1
    hostname: postgresql1
    restart: always
    ports:
      - '5433:5432'
    environment:
      - LEVEL=dev
      - POSTGRES_USER:'binomo'
      - POSTGRES_PASSWORD:'binomo'
      - POSTGRES_DB:'binomo'

  binomo:
    build:
      context: ./
    container_name: binomo
    hostname: binomo
    command: tail -f /dev/null
  
    ports:
      - '3001:3000'
      - '8081:8081'
    volumes:
      - ./:/app
    depends_on:
      - postgresql1