stage_select:
  s1: "staging"
  s2: "staging2"
  s3: "staging3"
  s4: "staging4"
  s5: "staging5"
  s6: "staging6"
  s7: "staging7"

project:
  binomo: "binomo"
  binpartner: "binpartner"
  statistics: "statistics"

frame_work:
  cucumber: "cucumber"
  rspec: "rspec"
