
fixed: "
  \tGiven Fixed"
percentage: "
  \tGiven Percentage"

activate: "
  \t\t When Select type tournament on activate
"
draft: "
  \t\tWhen Select type tournament on demand"

sum_deals: "
  \t\tWhen Created Tournament 'sum deals'"
max_balance: "
  \t\tWhen Created Tournament 'max demo balance'"

created_tournament: "
  \tGiven Tournament\n
    \t\tWhen Add data\n
    \tGiven Data from\n
    \tGiven Data to"

created_a_tournament?: "
  Then Result"
delete_all_tournaments: "
  Given Delete all tournaments"
participate: "
  \t\tWhen Participate"

repeat type loopead: "
  \t\t When Repeat type loopead
"
repeat type periodical: "
  \t\t When Repeat type periodical
"
quality create tournaments: "
  \t\tWhen Quality create tournaments
"
