# development:
#   adapter: async
#
# test:
#   adapter: async
#
# production:
#   adapter: redis
#   url: redis://0.0.0.0:8081
redis: &redis
  adapter: redis
  url: redis://0.0.0.0:8081

production: *redis

development:
  adapter: async

test:
  adapter: async
