development:
  adapter: postgresql
  encoding: utf8
  database: binomo
  host: 127.0.0.1
  port: 5432
  username: binomo
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: utf8
  database: binomo
  host: 127.0.0.1
  port: 5432
  username: binomo
  pool: 5
  timeout: 5000
