development:
  adapter: postgresql
  encoding: utf8
  database: binomo
  host: 172.20.0.2
  port: 5432
  username: binomo
  password: binomo
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: utf8
  database: binomo
  host: 172.20.0.2
  port: 5432
  username: binomo
  password: binomo
  pool: 5
  timeout: 5000
