development:
  adapter: postgresql
  encoding: utf8
  database: binomo
  host: postgresql
  port: 5432
  username: binomo
  password: binomo
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: utf8
  database: binomo
  host: postgresql
  port: 5432
  username: binomo
  password: binomo
  pool: 5
  timeout: 5000

  # CREATE ROLE binomo WITH LOGIN ENCRYPTED PASSWORD 'binomo';
  # CREATE DATABASE binomo WITH OWNER binomo;